# Generated by Django 3.2.7 on 2021-09-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiad',
            old_name='id_ad',
            new_name='id',
        ),
    ]
