# Generated by Django 3.2.7 on 2021-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_ad_apiad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiad',
            name='legajo',
            field=models.FloatField(),
        ),
    ]
