# Generated by Django 3.2.7 on 2021-09-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apiad_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiad',
            name='legajo',
            field=models.IntegerField(),
        ),
    ]
