# Generated by Django 3.2.7 on 2021-09-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apiad_legajo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIad',
            new_name='API',
        ),
    ]
